### ISSUE TITLE
[🚀 Feature]: Recommend to integrate AppiumBoot framework

### ISSUE THREAD

**Issue by shigebeyond** [appium/python-client#760]
I write [AppiumBoot](https://github.com/shigebeyond/AppiumBoot) to use yaml in test development, It's very simple to use Appium

[demo video](https://www.zhihu.com/zvideo/1542517089130147840)
[demo code](https://github.com/shigebeyond/AppiumBoot/tree/main/example)
some code like
```
# AppiumBoot/example/material/comp5.yml
# home page: click 5th cell
- click_by:
    xpath: /hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.recyclerview.widget.RecyclerView/android.widget.FrameLayout[5]/android.widget.LinearLayout # 按钮的xpath路径
  sleep: 1
# second page: click 3th demo
- click_by:
    xpath: /hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.RelativeLayout[2]
# thirth page: drag and move
  move_track: '360,1100;360,600;800,600;800,1600;100,1600;100,600'
# back to second page: click 4th demo
- back:
  click_by:
    xpath: /hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.RelativeLayout[4]
  swipe_up:
```
